const adverts =[
    {
      "id": 342,
      "name": "Ravenswood Australian Women's Art Prize",
      "created": "2018-11-12T12:16:00",
      "Code": "Ravenswood_2018",
      "Image": "images/advertisements/Ravenswood-Art-Prize-ArtPrizes-Call_2018.gif",
      "updated": "2018-11-13T10:47:00",
      "active": true,
      "url": "https://www.ravenswoodartprize.com.au/2019/artprize/home",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2018-11-12T00:00:00",
      "toDate": "2019-03-20T00:00:00",
      "category": "Home",
      "prizeid": 800,
      "ExhibitionBannerImage": "images/advertisements/art-work/Ravenswood_Exh_Banner.gif",
      "PrizeBannerImage": "images/advertisements/art-work/banner_Ravenswood-Art-Prize-ArtPrizes_Call_banner.gif",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 345,
      "name": "Naked and Nude",
      "created": "2018-12-20T10:03:00",
      "Code": "NakedNude_2019",
      "Image": "images/advertisements/Art Prizes tile N & N 19.jpg",
      "updated": "2019-01-14T17:40:00",
      "active": true,
      "url": "https://friendsmanningvalley.com.au/nakedandnude-art-prize/",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-01-01T00:00:00",
      "toDate": "2019-06-01T00:00:00",
      "category": "Home",
      "prizeid": 309,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 349,
      "name": "Ballarat International Foto Biennale Martin Kantor Portrait Prize",
      "created": "2019-01-09T17:43:00",
      "Code": "MartinKantor_2019",
      "Image": "images/advertisements/MartinKantor_CalltoEntry_Tile.jpg",
      "updated": null,
      "active": true,
      "url": "https://ballaratfoto.org/martin-kantor/",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-01-09T00:00:00",
      "toDate": "2019-05-31T00:00:00",
      "category": "Home",
      "prizeid": 789,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_MartinKantor_CalltoEntry_Banner.jpg",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 350,
      "name": "Lethbridge 20,000 Small Scale Art Award",
      "created": "2019-01-16T14:11:00",
      "Code": "Lethbridge_2019",
      "Image": "images/advertisements/lethbridge_Call_2019.jpg",
      "updated": "2019-02-05T21:04:00",
      "active": true,
      "url": "https://www.lethbridgegallery.com/microsite/lethbridge-20000-2019",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-01-16T00:00:00",
      "toDate": "2019-05-17T00:00:00",
      "category": "Home",
      "prizeid": 235,
      "ExhibitionBannerImage": "images/advertisements/art-work/exhibition banner 20 000 V1_1000.jpg",
      "PrizeBannerImage": "images/advertisements/art-work/banner_Lethbridge_Banner_2019.jpg",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 351,
      "name": "Rotary Art Spectacular",
      "created": "2019-01-25T11:51:00",
      "Code": "Rotary_2019",
      "Image": "images/advertisements/Rotary_call_2019.jpg",
      "updated": "2019-01-26T17:00:00",
      "active": true,
      "url": "https://www.lethbridgegallery.com/microsite/rotary-art-spectacular-2019",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-02-01T00:00:00",
      "toDate": "2019-03-22T00:00:00",
      "category": "Home",
      "prizeid": 883,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_Entry banner Rotary Art Spectacular 300 x 100pxl.jpg",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 352,
      "name": "Brisbane Portrait Prize",
      "created": "2019-01-26T16:39:00",
      "Code": "BPP_2019",
      "Image": "images/advertisements/BPP_call_2019.jpg",
      "updated": "2019-01-26T16:46:00",
      "active": true,
      "url": "https://www.brisbaneportraitprize.org",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-02-01T00:00:00",
      "toDate": "2019-08-23T00:00:00",
      "category": "Home",
      "prizeid": 882,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_Entry banner BRISBANE PORTRAIT PRIZE 300 x 100pxl INVERSE.jpg",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 353,
      "name": "R & M McGivern Art Prize",
      "created": "2019-01-29T17:28:00",
      "Code": "McGivern_2019",
      "Image": "images/advertisements/McGivern_Call_2019.gif",
      "updated": null,
      "active": true,
      "url": "https://mcgivernartprize.com/",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-02-04T00:00:00",
      "toDate": "2019-04-04T00:00:00",
      "category": "Home",
      "prizeid": 47,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_McGivern_banner_2019.gif",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 354,
      "name": "Deakin University Contemporary Small Sculpture Award",
      "created": "2019-01-31T11:49:00",
      "Code": "Deaking_2019",
      "Image": "images/advertisements/Deakin_Call_2019.gif",
      "updated": null,
      "active": true,
      "url": "http://www.deakin.edu.au/locations/melbourne-burwood-campus/art-gallery",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-01-31T00:00:00",
      "toDate": "2019-03-22T00:00:00",
      "category": "Home",
      "prizeid": 225,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_Deakin_Banner_2019.jpg",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 355,
      "name": "BIFB_open",
      "created": "2019-02-01T11:17:00",
      "Code": "BIFB_open 2019",
      "Image": "images/advertisements/BIFBOpenProgram_CalltoEntry_Tile.jpg",
      "updated": null,
      "active": true,
      "url": "https://ballaratfoto.org/open-program-step-1/",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-02-01T00:00:00",
      "toDate": "2019-05-31T00:00:00",
      "category": "Home",
      "prizeid": null,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_BIFBOpenProgram_CalltoEntry_Banner.jpg",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 356,
      "name": "Waverley Art Prize",
      "created": "2019-02-12T16:01:00",
      "Code": "Waverley_2019",
      "Image": "images/advertisements/Waverley_Call_UPDATED_2019.jpg",
      "updated": "2019-02-19T12:03:00",
      "active": true,
      "url": "http://wwas.org.au/waverley-art-prize/",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-03-01T00:00:00",
      "toDate": "2019-05-17T00:00:00",
      "category": "Home",
      "prizeid": 563,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_Waverley_Banner_2019.jpg",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 357,
      "name": "Footscray Art Prize",
      "created": "2019-02-13T16:37:00",
      "Code": "Footscray_2019",
      "Image": "images/advertisements/Footscray_Call_2019.gif",
      "updated": null,
      "active": true,
      "url": "https://www.footscrayartprize.com/",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-02-13T00:00:00",
      "toDate": "2019-03-15T00:00:00",
      "category": "Home",
      "prizeid": 756,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_Footscray_Banner_2019.gif",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 358,
      "name": "Bayside Art Awards",
      "created": "2019-02-18T12:28:00",
      "Code": "BaysideNSW_2019",
      "Image": "images/advertisements/Bayside_Call_2019.jpg",
      "updated": null,
      "active": true,
      "url": "https://www.bayside.nsw.gov.au/area/whats/bayside-art-awards",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-02-18T00:00:00",
      "toDate": "2019-03-17T00:00:00",
      "category": "Home",
      "prizeid": 891,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_Bayside_Banner_2019.jpg",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    },
    {
      "id": 359,
      "name": "Nillumbik Prize for Contemporary Art ",
      "created": "2019-02-19T10:24:00",
      "Code": "Nillumbik_2019",
      "Image": "images/advertisements/Nillumbik_Call_2019.gif",
      "updated": "2019-02-19T10:26:00",
      "active": true,
      "url": "http://www.nillumbik.vic.gov.au/nillumbikprize",
      "showOnMobile": true,
      "mobileBGColor": "ffffff",
      "mobileTextColour": "000000",
      "artprize_id": null,
      "advert_artwork": null,
      "fromDate": "2019-02-19T00:00:00",
      "toDate": "2019-04-12T00:00:00",
      "category": "Home",
      "prizeid": 890,
      "ExhibitionBannerImage": "",
      "PrizeBannerImage": "images/advertisements/art-work/banner_Nillumbik_banner_2019.gif",
      "ExhibitionBannerDateFrom": null,
      "ExhibitionBannerDateTo": null
    }
  ]

  export default adverts;