const artPrizes =[
    {
      "id": 756,
      "title": "Footscray Art Prize",
      "country": "Australia",
      "state": "VIC",
      "city": null,
      "close_date": "2019-03-15T00:00:00",
      "ExhibitionStartDate": "2019-06-20T00:00:00",
      "ExhibitionEndDate": "2019-07-20T00:00:00",
      "ApplicationsStartDate": "2018-11-23T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/Footscray Art Prize.jpg",
      "sponsored_start_date": "2019-02-13T00:00:00",
      "sponsored_end_date": "2019-03-15T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": true,
      "IntendedToEnter": true,
      "Currency": "AUD $",
      "PrizeAmount": 17500,
      "Location": "VIC, Australia",
      "State": "VIC",
      "Country": "Australia",
      "ViewCount": 28,
      "FollowCount": 88,
      "IntentToEnterCount": 16,
      "eligibility": "National Entries"
    },
    {
      "id": 891,
      "title": "Bayside Art Awards",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-03-17T00:00:00",
      "ExhibitionStartDate": "2019-04-06T00:00:00",
      "ExhibitionEndDate": "2019-03-28T00:00:00",
      "ApplicationsStartDate": "2019-01-21T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/Bayside Art Awards 2019.jpg",
      "sponsored_start_date": "2019-02-18T00:00:00",
      "sponsored_end_date": "2019-03-17T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 70000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 22,
      "FollowCount": 3,
      "IntentToEnterCount": 0,
      "eligibility": "National Entries"
    },
    {
      "id": 800,
      "title": "Ravenswood Australian Women's Art Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-03-20T00:00:00",
      "ExhibitionStartDate": "2019-06-01T00:00:00",
      "ExhibitionEndDate": "2019-06-09T00:00:00",
      "ApplicationsStartDate": "2018-11-06T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/Ravenswood Australian Women's Art Prize.jpg",
      "sponsored_start_date": "2018-11-12T00:00:00",
      "sponsored_end_date": "2019-06-09T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 40000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 25,
      "FollowCount": 131,
      "IntentToEnterCount": 48,
      "eligibility": "National Entries"
    },
    {
      "id": 225,
      "title": "Deakin University Contemporary Small Sculpture Award",
      "country": "Australia",
      "state": "VIC",
      "city": null,
      "close_date": "2019-03-22T00:00:00",
      "ExhibitionStartDate": "2019-05-29T00:00:00",
      "ExhibitionEndDate": "2019-07-12T00:00:00",
      "ApplicationsStartDate": "2019-01-31T00:00:00",
      "prize_type": "Sculpture",
      "prize_logo": "/images/prize_logos/Deakin University Contemporary Small Sculpture Award.jpg",
      "sponsored_start_date": "2019-01-31T00:00:00",
      "sponsored_end_date": "2019-07-12T00:00:00",
      "sponsored": true,
      "hidden": true,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 10000,
      "Location": "VIC, Australia",
      "State": "VIC",
      "Country": "Australia",
      "ViewCount": 10,
      "FollowCount": 106,
      "IntentToEnterCount": 11,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 883,
      "title": "Rotary Art Spectacular",
      "country": "Australia",
      "state": "QLD",
      "city": null,
      "close_date": "2019-03-22T00:00:00",
      "ExhibitionStartDate": "2019-05-13T00:00:00",
      "ExhibitionEndDate": "2019-05-17T00:00:00",
      "ApplicationsStartDate": "2019-02-01T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/Rotary Art Spectacular.jpg",
      "sponsored_start_date": "2019-02-01T00:00:00",
      "sponsored_end_date": "2019-03-22T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 17000,
      "Location": "QLD, Australia",
      "State": "QLD",
      "Country": "Australia",
      "ViewCount": 10,
      "FollowCount": 6,
      "IntentToEnterCount": 4,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 890,
      "title": "Nillumbik Prize for Contemporary Art ",
      "country": "Australia",
      "state": "VIC",
      "city": null,
      "close_date": "2019-04-12T00:00:00",
      "ExhibitionStartDate": "2019-05-30T00:00:00",
      "ExhibitionEndDate": "2019-07-21T00:00:00",
      "ApplicationsStartDate": "2019-02-11T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/The Nillumbik Prize for Contemporary Art .jpg",
      "sponsored_start_date": "2019-02-19T00:00:00",
      "sponsored_end_date": "2019-04-12T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 20000,
      "Location": "VIC, Australia",
      "State": "VIC",
      "Country": "Australia",
      "ViewCount": 14,
      "FollowCount": 3,
      "IntentToEnterCount": 2,
      "eligibility": "National Entries"
    },
    {
      "id": 235,
      "title": "Lethbridge 20,000 Small Scale Art Award",
      "country": "Australia",
      "state": "QLD",
      "city": null,
      "close_date": "2019-05-17T00:00:00",
      "ExhibitionStartDate": "2019-06-27T00:00:00",
      "ExhibitionEndDate": "2019-07-06T00:00:00",
      "ApplicationsStartDate": "2019-01-16T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/Lethbridge 10,000 Small Scale Art Award.jpg",
      "sponsored_start_date": "2019-01-16T00:00:00",
      "sponsored_end_date": "2019-07-06T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 22500,
      "Location": "QLD, Australia",
      "State": "QLD",
      "Country": "Australia",
      "ViewCount": 16,
      "FollowCount": 291,
      "IntentToEnterCount": 14,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 563,
      "title": "Waverley Art Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-05-17T00:00:00",
      "ExhibitionStartDate": "2019-07-11T00:00:00",
      "ExhibitionEndDate": "2019-07-21T00:00:00",
      "ApplicationsStartDate": "2019-02-18T00:00:00",
      "prize_type": "2D works",
      "prize_logo": null,
      "sponsored_start_date": "2019-03-01T00:00:00",
      "sponsored_end_date": "2019-05-17T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 12000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 12,
      "FollowCount": 177,
      "IntentToEnterCount": 14,
      "eligibility": "National Entries"
    },
    {
      "id": 789,
      "title": "Ballarat International Foto Biennale Martin Kantor Portrait Prize",
      "country": "Australia",
      "state": "VIC",
      "city": null,
      "close_date": "2019-05-31T00:00:00",
      "ExhibitionStartDate": "2019-08-23T00:00:00",
      "ExhibitionEndDate": "2019-10-20T00:00:00",
      "ApplicationsStartDate": "2018-09-24T00:00:00",
      "prize_type": "Photography",
      "prize_logo": "/images/prize_logos/Ballarat International Foto Biennale Martin Kantor Portrait Prize.png",
      "sponsored_start_date": "2019-01-09T00:00:00",
      "sponsored_end_date": "2019-10-20T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 15000,
      "Location": "VIC, Australia",
      "State": "VIC",
      "Country": "Australia",
      "ViewCount": 5,
      "FollowCount": 9,
      "IntentToEnterCount": 0,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 47,
      "title": "R & M McGivern Art Prize",
      "country": "Australia",
      "state": "VIC",
      "city": null,
      "close_date": "2019-06-28T00:00:00",
      "ExhibitionStartDate": "2019-11-30T00:00:00",
      "ExhibitionEndDate": "2020-02-02T00:00:00",
      "ApplicationsStartDate": "2019-01-17T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/R - M McGivern Art Prize.jpg",
      "sponsored_start_date": "2019-02-04T00:00:00",
      "sponsored_end_date": "2019-04-04T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 25000,
      "Location": "VIC, Australia",
      "State": "VIC",
      "Country": "Australia",
      "ViewCount": 16,
      "FollowCount": 32,
      "IntentToEnterCount": 2,
      "eligibility": "National Entries"
    },
    {
      "id": 309,
      "title": "Naked and Nude",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-06-30T00:00:00",
      "ExhibitionStartDate": "2019-09-07T00:00:00",
      "ExhibitionEndDate": "2019-10-13T00:00:00",
      "ApplicationsStartDate": "2018-12-20T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/Naked and Nude.jpg",
      "sponsored_start_date": "2019-01-01T00:00:00",
      "sponsored_end_date": "2019-06-01T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 31000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 13,
      "FollowCount": 143,
      "IntentToEnterCount": 12,
      "eligibility": "National Entries"
    },
    {
      "id": 882,
      "title": "Brisbane Portrait Prize",
      "country": "Australia",
      "state": "QLD",
      "city": null,
      "close_date": "2019-08-23T00:00:00",
      "ExhibitionStartDate": "2019-09-30T00:00:00",
      "ExhibitionEndDate": "2019-10-31T00:00:00",
      "ApplicationsStartDate": "2019-02-01T00:00:00",
      "prize_type": "Portraiture",
      "prize_logo": "/images/prize_logos/Brisbane Portrait Prize.jpg",
      "sponsored_start_date": "2019-02-01T00:00:00",
      "sponsored_end_date": "2019-08-23T00:00:00",
      "sponsored": true,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 72500,
      "Location": "QLD, Australia",
      "State": "QLD",
      "Country": "Australia",
      "ViewCount": 12,
      "FollowCount": 2,
      "IntentToEnterCount": 2,
      "eligibility": "Restricted"
    },
    {
      "id": 151,
      "title": "Moran Contemporary Photographic Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-03-06T00:00:00",
      "ExhibitionStartDate": "2019-05-04T00:00:00",
      "ExhibitionEndDate": "2019-06-02T00:00:00",
      "ApplicationsStartDate": "2019-01-16T00:00:00",
      "prize_type": "Photography",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 100000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 5,
      "FollowCount": 86,
      "IntentToEnterCount": 2,
      "eligibility": "National Entries"
    },
    {
      "id": 889,
      "title": "Northern Beaches Library Artists' Book Award ",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-03-08T00:00:00",
      "ExhibitionStartDate": "2019-05-02T00:00:00",
      "ExhibitionEndDate": "2019-06-09T00:00:00",
      "ApplicationsStartDate": "2018-10-01T00:00:00",
      "prize_type": "General",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 1500,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 5,
      "FollowCount": 1,
      "IntentToEnterCount": 0,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 437,
      "title": "Chelsea International Fine Art Competition",
      "country": "United States",
      "state": null,
      "city": "New York",
      "close_date": "2019-03-12T00:00:00",
      "ExhibitionStartDate": "2019-08-10T00:00:00",
      "ExhibitionEndDate": "2019-08-20T00:00:00",
      "ApplicationsStartDate": "2019-01-27T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/32nd Chelsea International Fine Art Competition.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "USD $",
      "PrizeAmount": 70000,
      "Location": "United States",
      "State": null,
      "Country": "United States",
      "ViewCount": 18,
      "FollowCount": 131,
      "IntentToEnterCount": 3,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 885,
      "title": "Art Olympia",
      "country": "Japan",
      "state": null,
      "city": "Tokyo",
      "close_date": "2019-03-15T00:00:00",
      "ExhibitionStartDate": "2019-06-08T00:00:00",
      "ExhibitionEndDate": "2019-06-29T00:00:00",
      "ApplicationsStartDate": "2018-09-15T00:00:00",
      "prize_type": "2D works",
      "prize_logo": "/images/prize_logos/Art Olympia.png",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "USD $",
      "PrizeAmount": 220000,
      "Location": "Japan",
      "State": null,
      "Country": "Japan",
      "ViewCount": 17,
      "FollowCount": 9,
      "IntentToEnterCount": 8,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 877,
      "title": "Great Lakes Art Society Open Exhibition 2019",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-03-22T00:00:00",
      "ExhibitionStartDate": "2019-04-14T00:00:00",
      "ExhibitionEndDate": "2019-04-28T00:00:00",
      "ApplicationsStartDate": "2018-12-01T00:00:00",
      "prize_type": "General",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 6000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 4,
      "FollowCount": 3,
      "IntentToEnterCount": 3,
      "eligibility": "National Entries"
    },
    {
      "id": 418,
      "title": "Milburn Art Prize",
      "country": "Australia",
      "state": "QLD",
      "city": null,
      "close_date": "2019-03-29T00:00:00",
      "ExhibitionStartDate": "2019-05-03T00:00:00",
      "ExhibitionEndDate": "2019-05-15T00:00:00",
      "ApplicationsStartDate": "2018-11-01T00:00:00",
      "prize_type": "2D works",
      "prize_logo": "/images/prize_logos/Milburn Art Prize.jpg",
      "sponsored_start_date": "2019-05-03T00:00:00",
      "sponsored_end_date": "2019-05-15T00:00:00",
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 10000,
      "Location": "QLD, Australia",
      "State": "QLD",
      "Country": "Australia",
      "ViewCount": 7,
      "FollowCount": 219,
      "IntentToEnterCount": 15,
      "eligibility": "National Entries"
    },
    {
      "id": 420,
      "title": "Magenta Artists Art and Photography Show",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-04-01T00:00:00",
      "ExhibitionStartDate": "2019-04-19T00:00:00",
      "ExhibitionEndDate": "2019-04-22T00:00:00",
      "ApplicationsStartDate": "2019-01-01T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/Magenta Artists Art and Photography Show.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 9000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 4,
      "FollowCount": 76,
      "IntentToEnterCount": 0,
      "eligibility": "National Entries"
    },
    {
      "id": 892,
      "title": "Stencil Art Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-04-01T00:00:00",
      "ExhibitionStartDate": "2019-09-12T00:00:00",
      "ExhibitionEndDate": "2020-09-30T00:00:00",
      "ApplicationsStartDate": "2018-06-01T00:00:00",
      "prize_type": "Street Art",
      "prize_logo": "/images/prize_logos/Stencil Art Prize.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 10000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 0,
      "IntentToEnterCount": 0,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 173,
      "title": "CLIP Award",
      "country": "Australia",
      "state": "WA",
      "city": null,
      "close_date": "2019-04-03T00:00:00",
      "ExhibitionStartDate": "2019-05-31T00:00:00",
      "ExhibitionEndDate": "2019-06-30T00:00:00",
      "ApplicationsStartDate": "2019-01-18T00:00:00",
      "prize_type": "Photography",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 4500,
      "Location": "WA, Australia",
      "State": "WA",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 38,
      "IntentToEnterCount": 1,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 575,
      "title": "YICCA - International Contest of Contemporary Art",
      "country": "Italy",
      "state": null,
      "city": "Palermo",
      "close_date": "2019-04-03T00:00:00",
      "ExhibitionStartDate": "2019-06-13T00:00:00",
      "ExhibitionEndDate": "2019-06-26T00:00:00",
      "ApplicationsStartDate": "2018-12-17T00:00:00",
      "prize_type": "Arts Festival",
      "prize_logo": "/images/prize_logos/YICCA 2014 Young International Contest of Contemporary Art.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "EUR €",
      "PrizeAmount": 4000,
      "Location": "Italy",
      "State": null,
      "Country": "Italy",
      "ViewCount": 6,
      "FollowCount": 27,
      "IntentToEnterCount": 1,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 5,
      "title": "Archibald Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-04-05T00:00:00",
      "ExhibitionStartDate": "2019-05-11T00:00:00",
      "ExhibitionEndDate": "2019-09-08T00:00:00",
      "ApplicationsStartDate": "2019-02-04T00:00:00",
      "prize_type": "Portraiture",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 105000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 12,
      "FollowCount": 212,
      "IntentToEnterCount": 2,
      "eligibility": "National Entries"
    },
    {
      "id": 775,
      "title": "Hadley's Art Prize",
      "country": "Australia",
      "state": "TAS",
      "city": null,
      "close_date": "2019-04-05T00:00:00",
      "ExhibitionStartDate": "2019-07-20T00:00:00",
      "ExhibitionEndDate": "2019-08-18T00:00:00",
      "ApplicationsStartDate": "2019-01-04T00:00:00",
      "prize_type": "2D works",
      "prize_logo": "/images/prize_logos/Hadley's Art Prize.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 100000,
      "Location": "TAS, Australia",
      "State": "TAS",
      "Country": "Australia",
      "ViewCount": 4,
      "FollowCount": 84,
      "IntentToEnterCount": 11,
      "eligibility": "National Entries"
    },
    {
      "id": 83,
      "title": "Sir John Sulman Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-04-05T00:00:00",
      "ExhibitionStartDate": "2019-05-11T00:00:00",
      "ExhibitionEndDate": "2019-09-08T00:00:00",
      "ApplicationsStartDate": "2019-02-04T00:00:00",
      "prize_type": "General",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 40000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 7,
      "FollowCount": 181,
      "IntentToEnterCount": 0,
      "eligibility": "National Entries"
    },
    {
      "id": 82,
      "title": "Wynne Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-04-05T00:00:00",
      "ExhibitionStartDate": "2019-05-11T00:00:00",
      "ExhibitionEndDate": "2019-09-08T00:00:00",
      "ApplicationsStartDate": "2019-02-04T00:00:00",
      "prize_type": "Landscape",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 66000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 7,
      "FollowCount": 203,
      "IntentToEnterCount": 4,
      "eligibility": "National Entries"
    },
    {
      "id": 7,
      "title": "Sunshine Coast Art Prize",
      "country": "Australia",
      "state": "QLD",
      "city": null,
      "close_date": "2019-04-08T00:00:00",
      "ExhibitionStartDate": "2019-07-24T00:00:00",
      "ExhibitionEndDate": "2019-09-15T00:00:00",
      "ApplicationsStartDate": "2018-01-30T00:00:00",
      "prize_type": "2D works",
      "prize_logo": "/images/prize_logos/Sunshine Coast Art Prize 2D.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 30000,
      "Location": "QLD, Australia",
      "State": "QLD",
      "Country": "Australia",
      "ViewCount": 10,
      "FollowCount": 238,
      "IntentToEnterCount": 3,
      "eligibility": "National Entries"
    },
    {
      "id": 629,
      "title": "Aspects Art Show Open",
      "country": "Australia",
      "state": "QLD",
      "city": null,
      "close_date": "2019-04-10T00:00:00",
      "ExhibitionStartDate": "2019-05-02T00:00:00",
      "ExhibitionEndDate": "2019-05-04T00:00:00",
      "ApplicationsStartDate": "2018-12-14T00:00:00",
      "prize_type": "General",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 22000,
      "Location": "QLD, Australia",
      "State": "QLD",
      "Country": "Australia",
      "ViewCount": 5,
      "FollowCount": 8,
      "IntentToEnterCount": 2,
      "eligibility": "National Entries"
    },
    {
      "id": 390,
      "title": "The Singleton Art Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-04-12T00:00:00",
      "ExhibitionStartDate": "2019-05-10T00:00:00",
      "ExhibitionEndDate": "2019-05-12T00:00:00",
      "ApplicationsStartDate": "2019-01-28T00:00:00",
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/The Singleton Art Prize.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 22000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 6,
      "FollowCount": 91,
      "IntentToEnterCount": 1,
      "eligibility": "National Entries"
    },
    {
      "id": 530,
      "title": "Premio Combat Prize",
      "country": "Italy",
      "state": null,
      "city": "Livorno",
      "close_date": "2019-04-13T00:00:00",
      "ExhibitionStartDate": "2019-06-22T00:00:00",
      "ExhibitionEndDate": "2019-07-13T00:00:00",
      "ApplicationsStartDate": "2018-12-14T00:00:00",
      "prize_type": "General",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "EUR €",
      "PrizeAmount": 25000,
      "Location": "Italy",
      "State": null,
      "Country": "Italy",
      "ViewCount": 0,
      "FollowCount": 72,
      "IntentToEnterCount": 0,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 610,
      "title": "Science without Borders Challenge",
      "country": "United States",
      "state": null,
      "city": "Landover",
      "close_date": "2019-04-22T00:00:00",
      "ExhibitionStartDate": null,
      "ExhibitionEndDate": null,
      "ApplicationsStartDate": "2019-01-23T00:00:00",
      "prize_type": "2D works",
      "prize_logo": "/images/prize_logos/Science without Borders® Challenge 2018.png",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "USD $",
      "PrizeAmount": 2100,
      "Location": "United States",
      "State": null,
      "Country": "United States",
      "ViewCount": 0,
      "FollowCount": 6,
      "IntentToEnterCount": 1,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 157,
      "title": "Sculpture by the Sea - Bondi",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-04-22T00:00:00",
      "ExhibitionStartDate": "2019-10-24T00:00:00",
      "ExhibitionEndDate": "2019-11-10T00:00:00",
      "ApplicationsStartDate": "2019-02-04T00:00:00",
      "prize_type": "Sculpture",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 190000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 26,
      "IntentToEnterCount": 0,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 192,
      "title": "Kilgour Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-04-28T00:00:00",
      "ExhibitionStartDate": "2019-08-03T00:00:00",
      "ExhibitionEndDate": "2019-10-13T00:00:00",
      "ApplicationsStartDate": "2019-01-14T00:00:00",
      "prize_type": "Portraiture",
      "prize_logo": "/images/prize_logos/Kilgour Prize.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 50000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 13,
      "FollowCount": 71,
      "IntentToEnterCount": 2,
      "eligibility": "National Entries"
    },
    {
      "id": 441,
      "title": "Lumen Prize",
      "country": "United Kingdom",
      "state": null,
      "city": "London",
      "close_date": "2019-05-03T00:00:00",
      "ExhibitionStartDate": "2019-10-24T00:00:00",
      "ExhibitionEndDate": "2019-10-24T00:00:00",
      "ApplicationsStartDate": "2019-02-15T00:00:00",
      "prize_type": "Digital and New Media",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "USD $",
      "PrizeAmount": 11000,
      "Location": "United Kingdom",
      "State": null,
      "Country": "United Kingdom",
      "ViewCount": 6,
      "FollowCount": 28,
      "IntentToEnterCount": 1,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 60,
      "title": "Olive Cotton Award for photographic portraiture",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-05-03T00:00:00",
      "ExhibitionStartDate": "2019-07-12T00:00:00",
      "ExhibitionEndDate": "2019-09-22T00:00:00",
      "ApplicationsStartDate": "2019-02-12T00:00:00",
      "prize_type": "Photography",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 24250,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 20,
      "IntentToEnterCount": 0,
      "eligibility": "National Entries"
    },
    {
      "id": 145,
      "title": "John Shaw Neilson Acquisitive Art Prize",
      "country": "Australia",
      "state": "SA",
      "city": null,
      "close_date": "2019-05-10T00:00:00",
      "ExhibitionStartDate": "2019-05-16T00:00:00",
      "ExhibitionEndDate": "2019-05-24T00:00:00",
      "ApplicationsStartDate": "2019-02-18T00:00:00",
      "prize_type": "General",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 10000,
      "Location": "SA, Australia",
      "State": "SA",
      "Country": "Australia",
      "ViewCount": 3,
      "FollowCount": 45,
      "IntentToEnterCount": 0,
      "eligibility": "National Entries"
    },
    {
      "id": 202,
      "title": "Arthur Guy Memorial Painting Prize",
      "country": "Australia",
      "state": "VIC",
      "city": "Bendigo",
      "close_date": "2019-06-07T00:00:00",
      "ExhibitionStartDate": "2019-09-14T00:00:00",
      "ExhibitionEndDate": "2019-12-15T00:00:00",
      "ApplicationsStartDate": "2019-02-11T00:00:00",
      "prize_type": "General",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 50000,
      "Location": "VIC, Australia",
      "State": "VIC",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 148,
      "IntentToEnterCount": 1,
      "eligibility": "National Entries"
    },
    {
      "id": 810,
      "title": "Still: National Still Life Award",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-06-10T00:00:00",
      "ExhibitionStartDate": "2019-09-20T00:00:00",
      "ExhibitionEndDate": "2019-11-16T00:00:00",
      "ApplicationsStartDate": "2019-02-11T00:00:00",
      "prize_type": "Still Life",
      "prize_logo": "/images/prize_logos/Still National Still Life Award.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 30000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 5,
      "FollowCount": 29,
      "IntentToEnterCount": 2,
      "eligibility": "National Entries"
    },
    {
      "id": 749,
      "title": "Sunny Art Prize",
      "country": "United Kingdom",
      "state": null,
      "city": "London",
      "close_date": "2019-06-30T00:00:00",
      "ExhibitionStartDate": "2019-10-01T00:00:00",
      "ExhibitionEndDate": "2019-10-31T00:00:00",
      "ApplicationsStartDate": "2018-09-15T00:00:00",
      "prize_type": "Emerging",
      "prize_logo": "/images/prize_logos/Sunny Art Prize.png",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "GBP £",
      "PrizeAmount": 3000,
      "Location": "United Kingdom",
      "State": null,
      "Country": "United Kingdom",
      "ViewCount": 4,
      "FollowCount": 39,
      "IntentToEnterCount": 3,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 867,
      "title": "Ceramic Break Sculpture Park Triennial Acquisitive Sculpture Prize 2019",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-07-01T00:00:00",
      "ExhibitionStartDate": "2019-08-23T00:00:00",
      "ExhibitionEndDate": "2020-01-31T00:00:00",
      "ApplicationsStartDate": "2018-07-01T00:00:00",
      "prize_type": "Sculpture",
      "prize_logo": "/images/prize_logos/Ceramic Break Sculpture Park Triennial Acquisitive Sculpture Prize 2019.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 12000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 4,
      "IntentToEnterCount": 0,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 879,
      "title": "Naracoorte National Art Prize",
      "country": "Australia",
      "state": "SA",
      "city": null,
      "close_date": "2019-07-12T00:00:00",
      "ExhibitionStartDate": "2019-09-22T00:00:00",
      "ExhibitionEndDate": "2019-10-27T00:00:00",
      "ApplicationsStartDate": "2018-11-21T00:00:00",
      "prize_type": "2D works",
      "prize_logo": "/images/prize_logos/2019 Naracoorte National Art Prize.png",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 12000,
      "Location": "SA, Australia",
      "State": "SA",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 5,
      "IntentToEnterCount": 7,
      "eligibility": "National and International Entries Allowed"
    },
    {
      "id": 54,
      "title": "Paddington Art Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-09-16T00:00:00",
      "ExhibitionStartDate": "2019-10-17T00:00:00",
      "ExhibitionEndDate": "2019-10-27T00:00:00",
      "ApplicationsStartDate": "2019-02-07T00:00:00",
      "prize_type": "Landscape",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 35000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 7,
      "FollowCount": 303,
      "IntentToEnterCount": 23,
      "eligibility": "National Entries"
    }
  ]

  export default artPrizes;