const exhibitions =[
    {
      "id": 834,
      "title": "International ARC Salon Competition",
      "country": "United States",
      "state": null,
      "city": "New York",
      "close_date": "2017-11-15T00:00:00",
      "ExhibitionStartDate": "2018-09-21T00:00:00",
      "ExhibitionEndDate": "2019-03-31T00:00:00",
      "ApplicationsStartDate": null,
      "prize_type": "General",
      "prize_logo": "/images/prize_logos/13th International ARC Salon Competition - Landscape Category.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "USD $",
      "PrizeAmount": 100000,
      "Location": "United States",
      "State": null,
      "Country": "United States",
      "ViewCount": 0,
      "FollowCount": 3,
      "IntentToEnterCount": 0,
      "eligibility": null
    },
    {
      "id": 371,
      "title": "Future Generation Art Prize",
      "country": "Ukraine",
      "state": null,
      "city": "Kiev",
      "close_date": "2018-06-29T00:00:00",
      "ExhibitionStartDate": "2019-02-01T00:00:00",
      "ExhibitionEndDate": "2019-04-14T00:00:00",
      "ApplicationsStartDate": "2018-04-16T00:00:00",
      "prize_type": "Emerging",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "EUR €",
      "PrizeAmount": 120000,
      "Location": "Ukraine",
      "State": null,
      "Country": "Ukraine",
      "ViewCount": 4,
      "FollowCount": 11,
      "IntentToEnterCount": 3,
      "eligibility": null
    },
    {
      "id": 630,
      "title": "Heysen Sculpture Biennial",
      "country": "Australia",
      "state": "SA",
      "city": null,
      "close_date": "2018-06-30T00:00:00",
      "ExhibitionStartDate": "2019-02-24T00:00:00",
      "ExhibitionEndDate": "2019-05-30T00:00:00",
      "ApplicationsStartDate": "2018-05-01T00:00:00",
      "prize_type": "Sculpture",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 0,
      "Location": "SA, Australia",
      "State": "SA",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 5,
      "IntentToEnterCount": 0,
      "eligibility": null
    },
    {
      "id": 39,
      "title": "Meroogal women's art prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2018-07-31T00:00:00",
      "ExhibitionStartDate": "2018-09-22T00:00:00",
      "ExhibitionEndDate": "2019-03-16T00:00:00",
      "ApplicationsStartDate": "2018-07-01T00:00:00",
      "prize_type": "General",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 10000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 34,
      "IntentToEnterCount": 0,
      "eligibility": null
    },
    {
      "id": 158,
      "title": "Sculpture by the Sea - Cottesloe",
      "country": "Australia",
      "state": "WA",
      "city": null,
      "close_date": "2018-08-19T00:00:00",
      "ExhibitionStartDate": "2019-03-02T00:00:00",
      "ExhibitionEndDate": "2019-03-19T00:00:00",
      "ApplicationsStartDate": "2018-07-01T00:00:00",
      "prize_type": "Sculpture",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 100000,
      "Location": "WA, Australia",
      "State": "WA",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 9,
      "IntentToEnterCount": 0,
      "eligibility": null
    },
    {
      "id": 866,
      "title": "The Basil Sellers Art Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2018-09-10T00:00:00",
      "ExhibitionStartDate": "2019-02-21T00:00:00",
      "ExhibitionEndDate": "2019-03-17T00:00:00",
      "ApplicationsStartDate": "2018-07-09T00:00:00",
      "prize_type": "2D works",
      "prize_logo": "/images/prize_logos/The Basil Sellers Art Prize.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 20000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 1,
      "FollowCount": 2,
      "IntentToEnterCount": 3,
      "eligibility": null
    },
    {
      "id": 209,
      "title": "National Photographic Portrait Prize",
      "country": "Australia",
      "state": "ACT",
      "city": null,
      "close_date": "2018-10-23T00:00:00",
      "ExhibitionStartDate": "2019-02-22T00:00:00",
      "ExhibitionEndDate": "2019-04-07T00:00:00",
      "ApplicationsStartDate": "2018-09-04T00:00:00",
      "prize_type": "Photography",
      "prize_logo": "/images/prize_logos/National Photographic Portrait Prize.jpg",
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 64844,
      "Location": "ACT, Australia",
      "State": "ACT",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 46,
      "IntentToEnterCount": 2,
      "eligibility": null
    },
    {
      "id": 102,
      "title": "Montalto Sculpture Prize",
      "country": "Australia",
      "state": "VIC",
      "city": null,
      "close_date": "2018-10-31T00:00:00",
      "ExhibitionStartDate": "2019-02-24T00:00:00",
      "ExhibitionEndDate": "2019-08-25T00:00:00",
      "ApplicationsStartDate": "2018-08-03T00:00:00",
      "prize_type": "Sculpture",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 42000,
      "Location": "VIC, Australia",
      "State": "VIC",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 21,
      "IntentToEnterCount": 0,
      "eligibility": null
    },
    {
      "id": 578,
      "title": "North Sydney Art Prize",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2018-10-31T00:00:00",
      "ExhibitionStartDate": "2019-03-02T00:00:00",
      "ExhibitionEndDate": "2019-03-17T00:00:00",
      "ApplicationsStartDate": "2018-08-15T00:00:00",
      "prize_type": "General",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 47500,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 0,
      "FollowCount": 58,
      "IntentToEnterCount": 12,
      "eligibility": null
    },
    {
      "id": 228,
      "title": "Adelaide Perry Prize for Drawing",
      "country": "Australia",
      "state": "NSW",
      "city": null,
      "close_date": "2019-01-09T00:00:00",
      "ExhibitionStartDate": "2019-03-01T00:00:00",
      "ExhibitionEndDate": "2019-03-29T00:00:00",
      "ApplicationsStartDate": "2018-10-10T00:00:00",
      "prize_type": "Drawing",
      "prize_logo": null,
      "sponsored_start_date": null,
      "sponsored_end_date": null,
      "sponsored": false,
      "hidden": false,
      "watched": false,
      "IntendedToEnter": false,
      "Currency": "AUD $",
      "PrizeAmount": 25000,
      "Location": "NSW, Australia",
      "State": "NSW",
      "Country": "Australia",
      "ViewCount": 4,
      "FollowCount": 255,
      "IntentToEnterCount": 20,
      "eligibility": null
    }
  ]
  export default exhibitions;